return {
    -- "nvim-neotest/neotest",
    -- dependencies = {
    --     -- Dependencies
    --     "nvim-neotest/nvim-nio",
    --     "nvim-lua/plenary.nvim",
    --     "antoinemadec/FixCursorHold.nvim",
    --     "nvim-treesitter/nvim-treesitter",
    --     -- Adapters
    --     "nvim-neotest/neotest-plenary",
    --     "marilari88/neotest-vitest",
    --     "fredrikaverpil/neotest-golang",
    -- },
    -- config = function()
    --     local neotest = require("neotest")
    --     neotest.setup({
    --         adapters = {
    --             require("neotest-plenary"),
    --             require("neotest-vitest"), -- Use the Vitest adapter
    --             require("neotest-golang"), -- Use the Golang adapter
    --         },
    --         status = { virtual_text = true },
    --         output = { open_on_run = true },
    --     })
    --
    --     vim.keymap.set("n", "<leader>tr", function()
    --         neotest.run.run({
    --             suite = false,
    --             testify = true,
    --         })
    --     end, { desc = "Debug: Running Nearest Test" })
    --
    --     vim.keymap.set("n", "<leader>tv", function()
    --         neotest.summary.toggle()
    --     end, { desc = "Debug: Summary Toggle" })
    --
    --     vim.keymap.set("n", "<leader>ts", function()
    --         neotest.run.run({
    --             suite = true,
    --             testify = true,
    --         })
    --     end, { desc = "Debug: Running Test Suite" })
    --
    --     vim.keymap.set("n", "<leader>td", function()
    --         neotest.run.run({
    --             suite = false,
    --             testify = true,
    --             strategy = "dap",
    --         })
    --     end, { desc = "Debug: Debug Nearest Test" })
    --
    --     vim.keymap.set("n", "<leader>to", function()
    --         neotest.output.open()
    --     end, { desc = "Debug: Open test output" })
    --
    --     vim.keymap.set("n", "<leader>ta", function()
    --         neotest.run.run(vim.fn.getcwd())
    --     end, { desc = "Debug: Open test output" })
    -- end,
}
